# Generated by Django 3.2.12 on 2022-04-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0003_alter_story_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='subtitle',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
